version: '3.8'

services:
  fingerprint-api:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
      - DATABASE_URL=sqlite:///./test.db
      - FINGERPRINT_READER=libfprint
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - db_data:/var/lib/sqlite

volumes:
  db_data: